### ISSUE TITLE
What is the 'Friendly Captcha License'?

### ISSUE THREAD

**Issue by YugoCode** [FriendlyCaptcha/friendly-pow#13]
Hey :)

I saw that most of the other repositories are MIT licensed, this here is under the 'Friendly Captcha License'. What does this exactly mean?

Am I allowed to use the PoW challenge library in an open source project?

**Comment by KirbyDE** [comment]
I'd like to know this as well.

**Comment by gzuidhof** [comment]
Thanks for your question! A bit of a long answer, sorry about that.

We provide parts of our stack open source, such as the frontend widget at [friendly-challenge](https://github.com/FriendlyCaptcha/friendly-challenge) and most of our integrations.

We made the decision to keep our friendly-pow repository as “source available” for now, which means we publish it here primarily for transparency purposes. Currently, the repository cannot be used for other projects without our prior permission.

The background is as follows: we are always further developing Friendly Captcha, and want to do so in a dedicated and sustainable way. Offering a reliable service has a lot more hooks and eyes to it than may be obvious at first, and frankly we need the revenue from our SaaS offering to sustain this and its further development. Friendly Captcha has a social mission as well as being a business: we do already offer our service for free to small to medium sized non-profit and private projects. 

Our widget is truly open source, but this bit we are keeping source available for now. We can’t offer support or warranty for this codebase, and parts of it we weren’t even using ourselves anymore on our backend. In the future we will likely be open sourcing more parts of our stack again.

If you have a concrete project for which you want to use this repository’s source code, feel free to send us an email (hello (at) friendlycaptcha.com) with a project description. Given the right project we are happy to provide you or your organisation a license (often for free) so you can use this code.

It is perhaps not the answer you were looking for, but I hope you can understand.

**Comment by TechnologyClassroom** [comment]
@YugoCode Earlier iterations are MIT: https://github.com/FriendlyCaptcha/friendly-pow/commit/68a15d597abdd5f9f49e900f5af4b22c4925f1bc#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

0.1.2 is MIT https://github.com/FriendlyCaptcha/friendly-pow/tree/01a1c9c4aa858d3517881347c3328b67575029a7

**Comment by dev-love** [comment]
All versions of friendly-pow are source-available only.

There is one option for you if you have a concrete, non-profit project for which you want to use this repository’s source code, feel free to send us an email (hello (at) friendlycaptcha.com) with a project description. Given the right project we are happy to provide you or your organisation a license (often for free) so you can use this code.

**Comment by TechnologyClassroom** [comment]
That statement is false as my deleted comment pointed out version 0.1.2 and prior are MIT.

It is deceiving to have the main pinned package be MIT and the required dependency library to be source available.  People rarely check the license of dependencies because of the nature of package management.  At a quick glance, FriendlyCaptcha is free software and open source, but this is not the case anymore.

**Comment by bryankaplan** [comment]
You might want to update the README to clarify this policy.

**Comment by dev-love** [comment]
You are right! I've just updated the README :)

**Comment by bodorjzsolt** [comment]
Hello,
I could not find the license "Friendly Captcha License" - could you list it in the repository or post a permanent link to it?

**Comment by TechnologyClassroom** [comment]
@bodorjzsolt The intent is that the Friendly Captcha License is proprietary. If you look in the forks, there are forks with the last free commit, but the project might need some updates since then. They'll probably delete this comment of mine too to keep covering it up, but this will go to your inbox at least.

There is also another new proof-of-work captcha alternative called [anubis](https://github.com/Xe/x/tree/master/cmd/anubis). I haven't tried it, but it sounds cool.

**Comment by gzuidhof** [comment]
Hi @TechnologyClassroom,

You are correct in that it's best to consider the `Friendly Captcha License` as proprietary source-available. In practice it's a license that limits its use, especially around not creating a competing service using this code (but also allowing use within our SDKs) - that makes it non-open source. That's no secret, there no nefarious other reasons or traps here. I hope that makes sense and you can understand.

In practice if you are looking for a proof-of-work library that runs in the browser, which you can use with an open source license, I would propose to look elsewhere (e.g. in anubis that you mentioned - I'm not familiar with the project however).
